kernel: Use elfutils-dev instead of libelf-dev
With kernel 5.0.6 we start seeing compile errors such as:

  HOSTCXX -fPIC scripts/gcc-plugins/randomize_layout_plugin.o
In file included from <stdin>:1:
/usr/include/libelf/libelf.h:28:5: error: "__LIBELF_INTERNAL__" is not defined, evaluates to 0 [-Werror=undef]
 #if __LIBELF_INTERNAL__
     ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

elutils-dev installs a different version of libelf.

Signed-off-by: Rolf Neugebauer <rn@rneugeba.io>