mount: Add missing argument to Printf
go_vet (via https://goreportcard.com/report/github.com/linuxkit/linuxkit)
reported:

    error: missing argument for Printf("%v"): format reads arg 2, have only 1 args (vet)
    error: wrong number of args for format in Printf call: 2 needed but 3 args (vet)

Signed-off-by: Ian Campbell <ijc@docker.com>